[tool.poetry]
name = "foocat_flu"
version = "0.1.0"
description = ""
authors = ["Frank Lu <franklu@live.ca>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
